# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a7107183eebaaed2abd227d9cafa6aff1b65b936ddbb851de4f9d39da805fc17e5f8eea6b4a0759264eb2c8689138259e72c6fc54b12812420f4830c4314de

test:
  secret_key_base: f1ca6db8ee52691c9586e4edad7a73c79cfc520e8e25fce512d4f3e229209adb7d43b91bbb26b9372a0502b213e0a56b6ad4ce019ff61f509f4a7c844fe17103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
